[package]
name = "nearssage_storage"
description = "Nearssages's storage 💿"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
type-rules = { version = "0.2", features = ["derive"] }
nearssage_commons = { path = "../commons" }
nearssage_schema = { path = "../schema" }
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1"
redb = "1.0"
arrayvec = "0.7"
rclite = "0.2"
atomic_refcell = "0.1"
email_address = "0.2"
phonenumber = "0.3"
geo = { version = "0.26", features = ["use-serde"] }
serde = { version = "1.0", features = ["derive"] }
paste = "1"
derive_more = "0.99"
either = "1"
anyhow = "1"

[dev-dependencies]
rand = "0.8"
tempfile = "3"
